# deploy/k8s/redis/redis-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: wallet
spec:
  replicas: 1
  selector: { matchLabels: { app: redis } }
  template:
    metadata: { labels: { app: redis } }
    spec:
      volumes:
        - name: redis-data
          persistentVolumeClaim: { claimName: redis-pvc }
      containers:
        - name: redis
          image: redis:7-alpine
          args: ["redis-server","--appendonly","no"]
          ports: [{ containerPort: 6379 }]
          volumeMounts:
            - { name: redis-data, mountPath: /data }