# deploy/k8s/wallet-db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wallet-db-secret
  namespace: wallet
type: Opaque
stringData:
  POSTGRES_USER: "wallet"
  POSTGRES_DB:   "walletdb"
  POSTGRES_PASSWORD: "walletpass"