# deploy/k8s/postgres/postgres-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: wallet
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi