server:
port: 8080

postgres:
dsn: "host=postgres dbname=walletdb user=wallet sslmode=disable"

redis:
addr: "redis:6379"
password: ""
db: 0

kafka:
brokers:
- "kafka:9092"
topic: "wallet.events"

ratelimit:
rps: 100
burst: 200