apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-server
  namespace: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-server
  template:
    metadata:
      labels:
        app: wallet-server
    spec:
      containers:
        - name: wallet-server
          image: host.docker.internal:5000/wallet-server:latest
          imagePullPolicy: Always
          # 环境变量从 ConfigMap + Secret 读取
          envFrom:
            - configMapRef:
                name: wallet-config
            - secretRef:
                name: wallet-db-secret
          ports:
            - containerPort: 8080
          # 挂载 config.yaml 到业务期望的路径
          volumeMounts:
            - name: wallet-config-file
              mountPath: /app/internal/config/config.yaml
              subPath: config.yaml
      # 声明挂载点
      volumes:
        - name: wallet-config-file
          configMap:
            name: wallet-config
            items:
              - key: config.yaml
                path: config.yaml
